2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Models/Todos/TodoItemCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace DotnetCoreDays.Models.Todos
{
    public class TodoItemCreateDto
    {
        [Required]
        [StringLength(256)]
        public string Text { get; set; }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Models/Todos/TodoItemDto.cs
using System.ComponentModel.DataAnnotations;

namespace DotnetCoreDays.Models.Todos
{
    public class TodoItemDto
    {
        public int Id { get; set; }

        [Required]
        [StringLength(256)]
        public string Text { get; set; }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Controllers/TodosController.cs
using System.Threading.Tasks;
using DotnetCoreDays.Db;
using DotnetCoreDays.Domain;
using DotnetCoreDays.Models.Todos;
using Microsoft.AspNetCore.Mvc;

namespace DotnetCoreDays.Controllers
{
    [Route("[controller]")]
    public class TodosController : Controller
    {
        private readonly TodoDbContext _dbContext;

        public TodosController(TodoDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] TodoItemCreateDto input)
        {
            var todoItem = new TodoItem { Text = input.Text };

            _dbContext.TodoItems.Add(todoItem);

            await _dbContext.SaveChangesAsync();

            return PartialView("~/Pages/Todos/_TodoItemOnList.cshtml", new TodoItemDto
            {
                Id = todoItem.Id,
                Text = todoItem.Text
            });
        }

        [HttpDelete]
        [Route("{id}")]
        public async Task Delete(int id)
        {
            var todoItem = await _dbContext.TodoItems.FindAsync(id);
            if (todoItem == null)
            {
                return;
            }

            todoItem.IsDeleted = true;

            await _dbContext.SaveChangesAsync();
        }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DotnetCoreDays.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return RedirectToPage("/Todos/Index");
        }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Pages/Todos/Index.cshtml.cs
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using DotnetCoreDays.Db;
using DotnetCoreDays.Models.Todos;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DotnetCoreDays.Pages.Todos
{
    public class IndexModel : PageModel
    {
        public IReadOnlyList<TodoItemDto> TodoItems { get; private set; }

        private readonly TodoDbContext _dbContext;

        public IndexModel(TodoDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task OnGetAsync()
        {
            var todoItems = await _dbContext.TodoItems.ToListAsync();

            TodoItems = todoItems
                .Select(t => new TodoItemDto
                {
                    Id = t.Id,
                    Text = t.Text
                })
                .ToImmutableList();
        }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Views/Shared/Components/Footer/FooterViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DotnetCoreDays.Views.Components.TodoCreateArea
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Pages/Index.cshtml
@page
@model DotnetCoreDays.Pages.IndexModel

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Pages/_Layout.cshtml
@using DotnetCoreDays.Views.Components.TodoCreateArea
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <title>Dotnet Core Days</title>

    <environment names="Development">
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    </environment>

    <environment names="Staging,Production">
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    </environment>

    @RenderSection("styles", false)

</head>

<body>

    @RenderBody()
    
    <vc:footer></vc:footer>
    
    @*@await Component.InvokeAsync(typeof(FooterViewComponent)) // Alternative of <vc:footer></vc:footer> *@

    <environment names="Development">
        <script src="~/lib/jQuery/dist/jquery.js"></script>
        <script src="~/js/jquery.serializeFormToObject.js"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/lib/jQuery/dist/jquery.min.js"></script>
        <script src="~/js/jquery.serializeFormToObject.min.js"></script>
    </environment>

    @RenderSection("scripts", false)

</body>

</html>

2017-11-11-DotnetCoreDays/src/DotnetCoreDays/Views/Shared/Components/Footer/Default.cshtml
<br />
<hr/>
<div>
    Dotnet Core Days / <email>info@@sample.com</email>
</div>